input = ".."
input_repo = f"{input}/Seroens-Repo-Files"
input_projects = f"{input_repo}/LevelEditorProjects"
input_graphics = f"{input_repo}/Graphics"
input_inits = f"{input_graphics}/Inits"
input_tiles_init = f"{input_graphics}/Init.txt"
input_reorganized_init = f"{input_inits}/ReorganizedInit.txt"
input_comms_init = f"{input_inits}/CommsInit.txt"
input_classic_init = f"{input_inits}/ClassicInit.txt"
input_separated_init = f"{input_inits}/ModdedSeparatedInit.txt"
input_materials = f"{input_repo}/Materials"
input_props = f"{input_repo}/Props"
input_props_init = f"{input_props}/Init.txt"
input_vanilla = f"{input_repo}/Vanilla Pack"

input_projects = f"{input_repo}/LevelEditorProjects"
input_templates = f"{input_projects}/Templates"
input_region_packs = f"{input_projects}/Region Packs"

website_source = "Website Source"
input_thumbnails = f"{website_source}/Thumbnails"
input_tiles_thumbnails = f"{input_thumbnails}/Tile Packs"


output = "../Seroens-Repo"
dist_path = f"{output}/Dist"
dist_packs_path = f"{dist_path}/Packs"
dist_region_packs = f"{output}/Dist/Region Packs"